### ISSUE TITLE
ImportError: cannot import name 'PasswordGenerator' from 'password_generator'

### ISSUE THREAD

**Issue by JANCOKRAIMUBAWOK** [tahaluindo/Gmail-BOTV2#5]
How to fix this ?
![image](https://user-images.githubusercontent.com/99043004/189721797-0b7e59a9-e9ca-4c2e-bb20-7a6984957b40.png)

**Comment by mrpaciko** [comment]
try pip install random-password-generator

**Comment by JANCOKRAIMUBAWOK** [comment]
> try pip install random-password-generator

Its work and fixed . then 
![image](https://user-images.githubusercontent.com/99043004/189726422-feaaa7ff-bcbb-4ab3-9c37-44d2fa53a444.png)

**Comment by modol2211** [comment]
> > try pip install random-password-generator
> 
> Its work and fixed . then module 'undetected_chromedriver' has no attribute 'install' . i was install undetected_chromedriver also chromedriver.exe ![image](https://user-images.githubusercontent.com/99043004/189726422-feaaa7ff-bcbb-4ab3-9c37-44d2fa53a444.png)

me too

**Comment by tahaluindo** [comment]
`git pull && python beta.py`

**Comment by tahaluindo** [comment]
This [Download Chrome And Extrack The Path](https://github.com/tahaluindo/Gmail-BOTV2/blob/main/chromedriver.exe)
